from io import BytesIO
from datetime import datetime
import json
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill, Border, Side
from openpyxl.chart import BarChart, Reference


async def generate_excel(calculation: dict, user_email: str) -> bytes:
    """
    Generate Excel workbook with 4 sheets:
    1. Summary
    2. Cost Details
    3. Input Configuration
    4. Report Info
    """
    buffer = BytesIO()
    wb = Workbook()
    
    # Sheet 1: Summary
    ws_summary = wb.active
    ws_summary.title = "Summary"
    
    # Title
    ws_summary.merge_cells('A1:E1')
    ws_summary['A1'] = "JADE Cloud Matrix — Pricing Report"
    ws_summary['A1'].font = Font(size=18, bold=True, color="003366")
    ws_summary['A1'].alignment = Alignment(horizontal='center')
    
    # Metadata
    ws_summary['A3'] = "Report ID:"
    ws_summary['B3'] = calculation['id']
    ws_summary['A4'] = "Type:"
    ws_summary['B4'] = calculation.get('calc_type', 'standard').upper()
    ws_summary['A5'] = "Generated By:"
    ws_summary['B5'] = user_email
    ws_summary['A6'] = "Generated At:"
    ws_summary['B6'] = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')
    ws_summary['A7'] = "Duration (months):"
    ws_summary['B7'] = calculation['duration_months']
    
    # Cost comparison table
    ws_summary['A9'] = "Provider"
    ws_summary['B9'] = "Monthly Cost"
    ws_summary['C9'] = "Annual Cost"
    ws_summary['D9'] = "Status"
    
    header_fill = PatternFill(start_color="003366", end_color="003366", fill_type="solid")
    for cell in ['A9', 'B9', 'C9', 'D9']:
        ws_summary[cell].font = Font(bold=True, color="FFFFFF")
        ws_summary[cell].fill = header_fill
    
    row = 10
    calc_type = calculation.get("calc_type", "standard")
    
    if calc_type == "standard":
        breakdowns = calculation.get("result_json", {}).get("provider_breakdowns", [])
        for bd in breakdowns:
            ws_summary[f'A{row}'] = bd["provider_name"]
            ws_summary[f'B{row}'] = bd["total_cost_monthly"]
            ws_summary[f'C{row}'] = bd["total_cost_annual"]
            ws_summary[f'D{row}'] = "Cheapest" if bd.get("is_cheapest") else ""
            
            if bd.get("is_cheapest"):
                green_fill = PatternFill(start_color="C8E6C9", end_color="C8E6C9", fill_type="solid")
                for col in ['A', 'B', 'C', 'D']:
                    ws_summary[f'{col}{row}'].fill = green_fill
            
            row += 1
    else:
        # For other types, show simple total
        result_json = calculation.get("result_json", {})
        ws_summary[f'A{row}'] = result_json.get("provider_name", "Total")
        ws_summary[f'B{row}'] = result_json.get("total_monthly", 0)
        ws_summary[f'C{row}'] = result_json.get("total_monthly", 0) * 12
        ws_summary[f'D{row}'] = ""
    
    # Sheet 2: Cost Details
    ws_details = wb.create_sheet(title="Cost Details")
    ws_details['A1'] = "Cost Details"
    ws_details['A1'].font = Font(size=14, bold=True)
    
    result_json = calculation.get("result_json", {})
    ws_details['A3'] = str(result_json)
    
    # Sheet 3: Input Configuration
    ws_input = wb.create_sheet(title="Input Configuration")
    ws_input['A1'] = "Input Configuration"
    ws_input['A1'].font = Font(size=14, bold=True)
    
    input_json = calculation.get("input_json", {})
    ws_input['A3'] = str(input_json)
    
    # Sheet 4: Report Info
    ws_info = wb.create_sheet(title="Report Info")
    ws_info['A1'] = "Report Information"
    ws_info['A1'].font = Font(size=14, bold=True)
    ws_info['A3'] = "Calculation ID:"
    ws_info['B3'] = calculation['id']
    ws_info['A4'] = "Type:"
    ws_info['B4'] = calculation.get('calc_type', 'standard')
    ws_info['A5'] = "Created At:"
    ws_info['B5'] = calculation.get('created_at', '')
    ws_info['A6'] = "Exported By:"
    ws_info['B6'] = user_email
    ws_info['A7'] = "Exported At:"
    ws_info['B7'] = datetime.utcnow().isoformat()
    
    # Save to buffer
    wb.save(buffer)
    buffer.seek(0)
    return buffer.read()
