from io import BytesIO
from datetime import datetime
import json
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.pdfgen import canvas


async def generate_pdf(calculation: dict, user_email: str) -> bytes:
    """
    Generate professional PDF report for a calculation.
    Varies by calc_type: standard, reserved, kubernetes, network
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=0.75*inch, bottomMargin=0.75*inch)
    story = []
    
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#003366'),
        spaceAfter=30,
        alignment=TA_CENTER,
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor('#003366'),
        spaceAfter=12,
    )
    
    # Header
    story.append(Paragraph("JADE Cloud Matrix", title_style))
    story.append(Paragraph("Cloud Pricing Intelligence Engine", styles['Normal']))
    story.append(Paragraph("Jade Global Software Pvt Ltd | Infra BU", styles['Normal']))
    story.append(Spacer(1, 0.3*inch))
    
    # Metadata
    calc_type = calculation.get("calc_type", "standard").upper()
    story.append(Paragraph(f"<b>Report Type:</b> {calc_type} Pricing Analysis", styles['Normal']))
    story.append(Paragraph(f"<b>Report ID:</b> {calculation['id']}", styles['Normal']))
    story.append(Paragraph(f"<b>Generated By:</b> {user_email}", styles['Normal']))
    story.append(Paragraph(f"<b>Generated At:</b> {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}", styles['Normal']))
    story.append(Paragraph(f"<b>Duration:</b> {calculation['duration_months']} months", styles['Normal']))
    story.append(Spacer(1, 0.3*inch))
    
    # Recommendation box
    if calculation.get("cheapest_provider"):
        story.append(Paragraph("Recommendation", heading_style))
        rec_text = f"<b>Cheapest Provider:</b> {calculation['cheapest_provider']}"
        story.append(Paragraph(rec_text, styles['Normal']))
        story.append(Spacer(1, 0.3*inch))
    
    # Type-specific content
    calc_type_val = calculation.get("calc_type", "standard")
    
    if calc_type_val == "standard":
        story.append(PageBreak())
        story.append(Paragraph("Provider Cost Comparison", heading_style))
        
        # Build comparison table
        table_data = [["Provider", "Compute/mo", "Storage/mo", "Total/mo", "Total/year"]]
        breakdowns = calculation.get("result_json", {}).get("provider_breakdowns", [])
        
        for bd in breakdowns:
            table_data.append([
                bd["provider_name"],
                f"${bd['compute_cost_monthly']:.2f}",
                f"${bd['storage_cost_monthly']:.2f}",
                f"${bd['total_cost_monthly']:.2f}",
                f"${bd['total_cost_annual']:.2f}",
            ])
        
        table = Table(table_data, colWidths=[1.5*inch, 1.2*inch, 1.2*inch, 1.2*inch, 1.2*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#003366')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ]))
        story.append(table)
    
    elif calc_type_val == "reserved":
        story.append(PageBreak())
        story.append(Paragraph("Reserved Instance Cost Analysis", heading_style))
        
        result_json = calculation.get("result_json", {})
        story.append(Paragraph(f"<b>Total Upfront Cost:</b> ${result_json.get('total_upfront', 0):.2f}", styles['Normal']))
        story.append(Paragraph(f"<b>Total Monthly Cost:</b> ${result_json.get('total_monthly', 0):.2f}", styles['Normal']))
        story.append(Paragraph(f"<b>Total Cost for Duration:</b> ${result_json.get('total_for_duration', 0):.2f}", styles['Normal']))
        story.append(Spacer(1, 0.2*inch))
        
        items = result_json.get("items", [])
        if items:
            table_data = [["Provider", "Instance", "Term", "Qty", "Upfront", "Monthly", "Savings %"]]
            for item in items:
                table_data.append([
                    item["provider_name"],
                    item["instance_type"],
                    item["term"],
                    str(item["quantity"]),
                    f"${item['upfront_cost']:.2f}",
                    f"${item['monthly_cost']:.2f}",
                    f"{item['savings_vs_ondemand']:.0f}%",
                ])
            
            table = Table(table_data)
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#003366')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ]))
            story.append(table)
    
    elif calc_type_val == "kubernetes":
        story.append(PageBreak())
        story.append(Paragraph("Kubernetes Cluster Cost Breakdown", heading_style))
        
        result_json = calculation.get("result_json", {})
        story.append(Paragraph(f"<b>Provider:</b> {result_json.get('provider_name', 'N/A')}", styles['Normal']))
        story.append(Paragraph(f"<b>Node Type:</b> {result_json.get('node_type', 'N/A')}", styles['Normal']))
        story.append(Paragraph(f"<b>Node Count:</b> {result_json.get('node_count', 0)}", styles['Normal']))
        story.append(Paragraph(f"<b>Node Cost/month:</b> ${result_json.get('node_cost_monthly', 0):.2f}", styles['Normal']))
        story.append(Paragraph(f"<b>Cluster Fee/month:</b> ${result_json.get('cluster_fee_monthly', 0):.2f}", styles['Normal']))
        story.append(Paragraph(f"<b>Total Monthly:</b> ${result_json.get('total_monthly', 0):.2f}", styles['Normal']))
        story.append(Paragraph(f"<b>Total for Duration:</b> ${result_json.get('total_for_duration', 0):.2f}", styles['Normal']))
    
    elif calc_type_val == "network":
        story.append(PageBreak())
        story.append(Paragraph("Network Data Transfer Costs", heading_style))
        
        result_json = calculation.get("result_json", {})
        breakdowns = result_json.get("provider_breakdowns", [])
        
        if breakdowns:
            table_data = [["Provider", "Destination", "Transfer GB", "Free Tier", "Billable GB", "Cost/mo"]]
            for bd in breakdowns:
                table_data.append([
                    bd["provider_name"],
                    bd["destination_type"],
                    f"{bd['transfer_gb']:.2f}",
                    f"{bd['free_tier_gb']:.2f}",
                    f"{bd['billable_gb']:.2f}",
                    f"${bd['cost_monthly']:.2f}",
                ])
            
            table = Table(table_data)
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#003366')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ]))
            story.append(table)
        
        story.append(Spacer(1, 0.2*inch))
        story.append(Paragraph(f"<b>Total Monthly Cost:</b> ${result_json.get('total_monthly', 0):.2f}", styles['Normal']))
    
    # Input configuration page
    story.append(PageBreak())
    story.append(Paragraph("Input Configuration", heading_style))
    input_json = calculation.get("input_json", {})
    story.append(Paragraph(f"<pre>{json.dumps(input_json, indent=2)}</pre>", styles['Code']))
    
    # Build PDF
    doc.build(story)
    
    buffer.seek(0)
    return buffer.read()
